#pragma once

#define IDI_PULSE 101
#define IDR_EMPTY_FOLDER_SVG 102
#define IDR_NO_SELECTION_SVG 103
#define IDR_RECENT_EMPTY_SVG 104
#define IDR_STARRED_EMPTY_SVG 105
#define IDR_EXCLUDE_EMPTY_SVG 106
#define IDR_FLUENT_CUT_SVG 107
#define IDR_FLUENT_COPY_SVG 108
#define IDR_FLUENT_PASTE_SVG 109
#define IDR_FLUENT_RENAME_SVG 110
#define IDR_FLUENT_DELETE_SVG 111
#define IDR_FLUENT_STAR_SVG 112
#define IDR_FLUENT_HISTORY_SVG 113
#define IDR_FLUENT_DESKTOP_SVG 114
#define IDR_FLUENT_DOWNLOADS_SVG 115
#define IDR_FLUENT_RECYCLE_SVG 116
#define IDR_FLUENT_DRIVE_SVG 117
#define IDR_FLUENT_FOLDER_SVG 118
#define IDR_FLUENT_NETWORK_SVG 119
#define IDR_FLUENT_SEARCH_SVG 120
#define IDR_FLUENT_APPS_SVG 121
#define IDR_FLUENT_PANEL_SVG 122
#define IDR_FLUENT_PANEL_CLOSE_SVG 123
#define IDR_FLUENT_ADD_SVG 124
#define IDR_FLUENT_OMNIBAR_SEARCH_SVG 125
