#ifndef PULSE_STRING_IDS_H
#define PULSE_STRING_IDS_H

#define IDS_SETTINGS                    1000
#define IDS_SETTINGS_GENERAL            1001
#define IDS_SETTINGS_SEARCH_INDEX       1002
#define IDS_SETTINGS_CONTEXT_MENU       1003
#define IDS_SETTINGS_APPEARANCE         1004
#define IDS_SETTINGS_THEME_COLOR        1005
#define IDS_SETTINGS_THEME_COLOR_DESC   1006
#define IDS_SETTINGS_WINDOW_EFFECT      1007
#define IDS_SETTINGS_WINDOW_EFFECT_DESC 1008
#define IDS_EFFECT_NONE                 1009
#define IDS_EFFECT_ACRYLIC              1010
#define IDS_EFFECT_MICA                 1011
#define IDS_EFFECT_MICA_ALT             1012
#define IDS_SETTINGS_ROW_HEIGHT         1013
#define IDS_SETTINGS_ROW_HEIGHT_DESC    1014
#define IDS_DENSITY_COMPACT             1015
#define IDS_DENSITY_STANDARD            1016
#define IDS_DENSITY_COMFORTABLE         1017
#define IDS_SETTINGS_TRAY_ICON          1018
#define IDS_SETTINGS_TRAY_ICON_DESC     1019
#define IDS_TRAY_ICON_SMALL             1020
#define IDS_TRAY_ICON_STANDARD          1021
#define IDS_TRAY_ICON_LARGE             1022
#define IDS_SETTINGS_LANGUAGE           1023
#define IDS_SETTINGS_LANGUAGE_DESC      1024
#define IDS_LANGUAGE_SYSTEM             1025
#define IDS_LANGUAGE_ZH_CN              1026
#define IDS_LANGUAGE_EN_US              1027
#define IDS_SETTINGS_WALLPAPER          1028
#define IDS_SETTINGS_WALLPAPER_DESC     1029
#define IDS_CHOOSE_IMAGE                1030
#define IDS_CLEAR                       1031
#define IDS_SETTINGS_STARTUP_SHUTDOWN   1032
#define IDS_SETTINGS_LAUNCH             1033
#define IDS_SETTINGS_LAUNCH_DESC        1034
#define IDS_SETTINGS_KEEP_RUNNING       1035
#define IDS_SETTINGS_KEEP_RUNNING_DESC  1036
#define IDS_SETTINGS_OPEN_FOLDERS       1037
#define IDS_SETTINGS_OPEN_FOLDERS_DESC  1038
#define IDS_QUICK_PREVIEW               1039
#define IDS_PREVIEW_CLOUD_ONLY          1040
#define IDS_PREVIEW_LOADING             1041
#define IDS_PREVIEW_HOST_UNAVAILABLE    1042
#define IDS_PREVIEW_SAFE_MODE_DISABLED  1043
#define IDS_PREVIEW_NO_HANDLER          1044
#define IDS_PREVIEW_FILE_UNAVAILABLE    1045
#define IDS_PREVIEW_CANNOT_RENDER       1046
#define IDS_CLOSE                       1047
#define IDS_THIS_PC                     1048
#define IDS_STARRED_ITEMS               1049
#define IDS_RECENT                      1050
#define IDS_SEARCH                      1051
#define IDS_TAG                         1052
#define IDS_DESKTOP                     1053
#define IDS_LOCAL_DISK                  1054
#define IDS_SIDEBAR_WORKSPACES          1055
#define IDS_SIDEBAR_QUICK_ACCESS        1056
#define IDS_SIDEBAR_SAVED_SEARCHES      1057
#define IDS_SIDEBAR_DRIVES              1058
#define IDS_SIDEBAR_TAGS                1059
#define IDS_SIDEBAR_NETWORK_LOCATIONS   1060
#define IDS_SERVER                      1061
#define IDS_CURRENT                     1062
#define IDS_CURRENT_SERVER              1063
#define IDS_PROJECT_FORMAT              1064
#define IDS_STATUS_ITEMS_FORMAT         1065
#define IDS_NOT_SELECTED                1066
#define IDS_SELECTED_ONE_FORMAT         1067
#define IDS_SELECTED_COUNT_FORMAT       1068
#define IDS_THEME_DARK                  1069
#define IDS_THEME_LIGHT                 1070
#define IDS_COLUMN_NAME                 1071
#define IDS_COLUMN_PATH                 1072
#define IDS_COLUMN_MODIFIED             1073
#define IDS_COLUMN_RECENT_OPENED        1074
#define IDS_COLUMN_TYPE                 1075
#define IDS_COLUMN_SIZE                 1076
#define IDS_FILTER_ALL                  1077
#define IDS_FILTER_FOLDERS              1078
#define IDS_FILTER_FILES                1079
#define IDS_TYPE_FOLDER                 1080
#define IDS_TYPE_FILE                   1081
#define IDS_TYPE_TEXT_DOCUMENT          1082
#define IDS_TYPE_IMAGE                  1083
#define IDS_TYPE_VIDEO                  1084
#define IDS_TYPE_AUDIO                  1085
#define IDS_TYPE_ARCHIVE                1086
#define IDS_TYPE_APPLICATION            1087
#define IDS_UNAVAILABLE                 1088
#define IDS_NO_MATCHES                  1089
#define IDS_NO_STARRED                  1090
#define IDS_NO_RECENT                   1091
#define IDS_NO_FILTERED_RESULTS          1092
#define IDS_NO_STARRED_MESSAGE          1093
#define IDS_TRY_OTHER_TYPE              1094
#define IDS_NO_RECENT_MESSAGE           1095
#define IDS_NO_CONTENT                  1096
#define IDS_FOLDER_EMPTY                1097
#define IDS_FOLDER_EMPTY_MESSAGE        1098
#define IDS_NEW_FOLDER                  1099
#define IDS_FILTER_PLACEHOLDER          1100
#define IDS_NEW                         1101
#define IDS_ITEMS_COUNT_FORMAT          1102
#define IDS_STAGING_TRAY                1103
#define IDS_STAGING_TRAY_HELPER         1104
#define IDS_RELEASE                     1105
#define IDS_TOTAL_SIZE_FORMAT           1106
#define IDS_TOTAL_SIZE_BATCHES_FORMAT   1107
#define IDS_CLEAR_ALL                   1108
#define IDS_DETAILS_NO_SELECTION        1109
#define IDS_DETAILS_BASIC               1110
#define IDS_DETAILS_TAGS                1111
#define IDS_DETAILS_ATTRIBUTES          1112
#define IDS_DETAILS_SECURITY            1113
#define IDS_DETAILS_OTHER               1114
#define IDS_OPEN                        1115
#define IDS_OPEN_NEW_TAB                1116
#define IDS_COPY_PATH                   1117
#define IDS_MORE                        1118
#define IDS_INFORMATION                 1119
#define IDS_LOCATION                    1120
#define IDS_KNOWN_SIZE                  1121
#define IDS_CONTAINS                    1122
#define IDS_CREATED                     1123
#define IDS_MODIFIED_TIME               1124
#define IDS_LAST_ACCESSED               1125
#define IDS_READ_ONLY                   1126
#define IDS_HIDDEN                      1127
#define IDS_ADVANCED                    1128
#define IDS_ADD_TAG                     1129
#define IDS_OWNER                       1130
#define IDS_LOADING_ELLIPSIS            1131
#define IDS_CHANGE                      1132
#define IDS_PERMISSIONS                 1133
#define IDS_DRIVE                       1134
#define IDS_FILE_SYSTEM                 1135
#define IDS_FREE_SPACE                  1136
#define IDS_CALCULATING                 1137
#define IDS_EMPTY_FILE                  1138
#define IDS_HEX_PREFIX                  1139
#define IDS_TEXT_PREFIX                 1140
#define IDS_TRUNCATED_SUFFIX            1141
#define IDS_ONLINE_TO_PREVIEW           1142
#define IDS_PREVIEW_MOVED               1143
#define IDS_PREVIEW_IMAGE_DECODE        1144
#define IDS_PREVIEW_NO_SYSTEM_PROVIDER  1145
#define IDS_PREVIEW_LOAD_FAILED         1146
#define IDS_PREVIEW_UNSUPPORTED         1147
#define IDS_SETTINGS_FULL_INDEX         1148
#define IDS_SETTINGS_USER_INDEX         1149
#define IDS_SETTINGS_FULL_INDEX_DESC    1150
#define IDS_SETTINGS_USER_INDEX_DESC    1151
#define IDS_INDEX_STATUS                1152
#define IDS_INDEX_LOCATION              1153
#define IDS_REBUILD                     1154
#define IDS_OPEN_LOCATION               1155
#define IDS_CHANGE_LOCATION             1156
#define IDS_INSTALL_SERVICE             1157
#define IDS_LOCAL_DRIVES                1158
#define IDS_EXCLUSIONS                  1159
#define IDS_ADD_FOLDER                  1160
#define IDS_NO_EXCLUDED_FOLDERS         1161
#define IDS_NO_EXCLUDED_FOLDERS_DESC    1162
#define IDS_REMOVE                      1163
#define IDS_SERVER_FOLDERS              1164
#define IDS_RESCAN                      1165
#define IDS_NO_SERVER_FOLDERS_DESC      1166
#define IDS_CONTEXT_MENU_DESC           1167
#define IDS_CONTEXT_SOFTWARE            1168
#define IDS_CONTEXT_OPEN_WITH           1169
#define IDS_CONTEXT_SHARE               1170
#define IDS_CONTEXT_SYSTEM              1171
#define IDS_CONTEXT_PRINT               1172
#define IDS_CONTEXT_SOFTWARE_DESC       1173
#define IDS_CONTEXT_OPEN_WITH_DESC      1174
#define IDS_CONTEXT_SHARE_DESC          1175
#define IDS_CONTEXT_SYSTEM_DESC         1176
#define IDS_CONTEXT_PRINT_DESC          1177
#define IDS_RESTORE_DEFAULTS            1178
#define IDS_TOOLTIP_CLOSE_TAB           1179
#define IDS_TOOLTIP_NEW_TAB             1180
#define IDS_TOOLTIP_TOGGLE_THEME        1181
#define IDS_WINDOW_EFFECT_FORMAT        1182
#define IDS_TOOLTIP_CHOOSE_BACKGROUND   1183
#define IDS_TOOLTIP_CLEAR_BACKGROUND    1184
#define IDS_TOOLTIP_FOLLOW_ACCENT       1185
#define IDS_TOOLTIP_ADD_EXCLUSION       1186
#define IDS_TOOLTIP_REMOVE_EXCLUSION    1187
#define IDS_MINIMIZE                    1188
#define IDS_RESTORE                     1189
#define IDS_MAXIMIZE                    1190
#define IDS_BACK                        1191
#define IDS_FORWARD                     1192
#define IDS_UP                          1193
#define IDS_REFRESH                     1194
#define IDS_CUT_SHORTCUT                1195
#define IDS_COPY_SHORTCUT               1196
#define IDS_PASTE_SHORTCUT              1197
#define IDS_RENAME_SHORTCUT             1198
#define IDS_DELETE_SHORTCUT             1199
#define IDS_SPLIT_LAYOUT                1200
#define IDS_COLLAPSE_DETAILS            1201
#define IDS_EXPAND_DETAILS              1202
#define IDS_MEDIUM_ICONS                1203
#define IDS_VIEW                        1204
#define IDS_FILTER_CURRENT              1205
#define IDS_RESIZE_SPLIT                1206
#define IDS_FAVORITE                    1207
#define IDS_MORE_ACTIONS                1208
#define IDS_RENAME                      1209
#define IDS_RESIZE_DETAILS              1210
#define IDS_PREVIEW_FIT                 1211
#define IDS_EXPAND_COLLAPSE             1212
#define IDS_SYSTEM_ATTRIBUTES           1213
#define IDS_STAR                        1214
#define IDS_UNPIN                       1215
#define IDS_UNDO                        1216
#define IDS_CUT                         1217
#define IDS_COPY                        1218
#define IDS_PASTE                       1219
#define IDS_DELETE                      1220
#define IDS_PROPERTIES                  1221
#define IDS_OPEN_TERMINAL_HERE          1222
#define IDS_PIN_WORKSPACE               1223
#define IDS_PIN_NETWORK                 1224
#define IDS_TAGS_ELLIPSIS               1225
#define IDS_NEW_TEXT_DOCUMENT           1226
#define IDS_FOLDER                      1227
#define IDS_TEXT_DOCUMENT               1228
#define IDS_LAYOUT_SINGLE               1229
#define IDS_LAYOUT_VERTICAL             1230
#define IDS_LAYOUT_HORIZONTAL           1231
#define IDS_LAYOUT_THREE                1232
#define IDS_LAYOUT_FOUR                 1233
#define IDS_COPY_TO_TARGET              1234
#define IDS_MOVE_TO_TARGET              1235
#define IDS_VIEW_EXTRA_LARGE            1236
#define IDS_VIEW_LARGE                  1237
#define IDS_VIEW_SMALL                  1238
#define IDS_VIEW_LIST                   1239
#define IDS_VIEW_DETAILS                1240
#define IDS_VIEW_TILES                  1241
#define IDS_VIEW_CONTENT                1242
#define IDS_DETAILS_PANE                1243
#define IDS_SHOW_ALL_RESULTS            1244
#define IDS_HISTORY_PATH                1245
#define IDS_FILES_FOLDERS_FORMAT        1246
#define IDS_FILES_ONLY_FORMAT           1247
#define IDS_FOLDERS_ONLY_FORMAT         1248
#define IDS_MULTIPLE_LOCATIONS          1249
#define IDS_CONTAINS_FORMAT             1250
#define IDS_SEARCH_RESULTS_FORMAT       1251
#define IDS_SEARCH_RESULTS_PARTIAL_FMT  1252
#define IDS_SAVED_SEARCH_UNAVAILABLE    1253
#define IDS_CANNOT_OPEN_SAVED_SEARCH    1254
#define IDS_SAVED_SEARCH_REMOVED        1255
#define IDS_SCANNED_FILES_FORMAT        1256
#define IDS_RESULT_LIMIT_TITLE          1257
#define IDS_RESULT_LIMIT_MESSAGE        1258
#define IDS_SEARCH_INCOMPLETE           1259
#define IDS_ERROR_CODE_FORMAT           1260
#define IDS_SEARCH_LOADING_FORMAT       1261
#define IDS_CACHE                       1262
#define IDS_REFRESHING                  1263
#define IDS_OFFLINE                     1264
#define IDS_CANNOT_OPEN                 1265
#define IDS_CACHED_READ_ONLY            1266
#define IDS_DIRECTORY_UNAVAILABLE       1267
#define IDS_OMNIBAR_COMMAND             1268
#define IDS_OMNIBAR_PROJECT             1269
#define IDS_OMNIBAR_DEFAULT             1270
#define IDS_SEARCHING                   1271
#define IDS_SEARCH_INPUT_PROMPT         1272
#define IDS_IMAGES                      1273
#define IDS_ALL_FILES                   1274
#define IDS_CHOOSE_INDEX_LOCATION       1275
#define IDS_OPEN_IN_TERMINAL            1276
#define IDS_COMPUTE_SIZE                1277
#define IDS_SYSTEM_MENU                 1278
#define IDS_REMOVABLE_DISK              1279
#define IDS_FIXED_DISK                  1280
#define IDS_PERFORMANCE_FORMAT          1281
#define IDS_SETTINGS_ABOUT_DIAGNOSTICS  1282
#define IDS_ABOUT_PULSE                 1283
#define IDS_VERSION_FORMAT              1284
#define IDS_BUILD_ID_FORMAT             1285
#define IDS_DIAGNOSTICS                 1286
#define IDS_DIAGNOSTICS_DESC            1287
#define IDS_OPEN_DIAGNOSTICS            1288
#define IDS_CLEAR_DIAGNOSTICS           1289
#define IDS_EXPORT_DIAGNOSTICS          1290
#define IDS_DIAGNOSTICS_CLEAR_CONFIRM   1291
#define IDS_DIAGNOSTICS_PRIVACY_TITLE   1292
#define IDS_DIAGNOSTICS_PRIVACY_MESSAGE 1293
#define IDS_DIAGNOSTICS_INCLUDE_SERVICE 1294
#define IDS_DIAGNOSTICS_EXPORT_LOCATION 1295
#define IDS_DIAGNOSTICS_EXPORT_FAILED   1296
#define IDS_UPDATE                      1297
#define IDS_UPDATE_DESC                 1298
#define IDS_CHECK_FOR_UPDATES           1299
#define IDS_CHECKING_UPDATES            1300
#define IDS_UPDATE_DISABLED             1301
#define IDS_UPDATE_UP_TO_DATE           1302
#define IDS_UPDATE_AVAILABLE_FORMAT     1303
#define IDS_UPDATE_FAILED               1304
#define IDS_UPDATE_UNSUPPORTED_WINDOWS  1305
#define IDS_DOWNLOAD_UPDATE             1306
#define IDS_INSTALLER_HASH_FORMAT       1307
#define IDS_DIAGNOSTICS_EXPORTING       1308
#define IDS_DIAGNOSTICS_CLEAR_FAILED    1309
#define IDS_PREVIEW_DECODED_FORMAT      1310
#define IDS_SELECT_ALL                  1311
#define IDS_RECYCLE_BIN                 1312
#define IDS_RECYCLE_OCCUPANCY_FORMAT    1313
#define IDS_EMPTY_RECYCLE_BIN           1314
#define IDS_EMPTY_RECYCLE_CONFIRM_TITLE 1315
#define IDS_EMPTY_RECYCLE_CONFIRM       1316
#define IDS_COLUMN_DELETED              1317
#define IDS_RECYCLE_EMPTY               1318
#define IDS_RECYCLE_EMPTY_MESSAGE       1319
#define IDS_BATCH_RENAME                1320
#define IDS_FIND                        1321
#define IDS_REPLACE                     1322
#define IDS_PREFIX                      1323
#define IDS_SUFFIX                      1324
#define IDS_NUMBER                      1325
#define IDS_APPLY                       1326
#define IDS_PREVIEW                     1327
#define IDS_UNCHANGED                   1328
#define IDS_NAME_COLLISION              1329
#define IDS_INVALID_NAME                1330
#define IDS_CANCEL                      1331
#define IDS_PERMANENT_DELETE            1332
#define IDS_INVERT_SELECTION            1333
#define IDS_SELECT_WILDCARD             1334
#define IDS_SELECT_WILDCARD_HINT        1335
#define IDS_BATCH_RENAME_PATTERN        1336
#define IDS_BATCH_RENAME_PATTERN_HINT   1337
#define IDS_BATCH_RENAME_INCLUDE_EXT    1338
#define IDS_BATCH_RENAME_START_FROM     1339
#define IDS_BATCH_RENAME_CHIP_NUMBER    1340
#define IDS_BATCH_RENAME_CHIP_PADDED    1341
#define IDS_BATCH_RENAME_CHIP_EXT       1342
#define IDS_BATCH_RENAME_WILL_RENAME    1343
#define IDS_BATCH_RENAME_SUMMARY        1344
#define IDS_SETTINGS_DUPLICATES         1345
#define IDS_DUP_SCOPE_FOLDER            1346
#define IDS_DUP_SCOPE_DRIVE             1347
#define IDS_DUP_SCOPE_ALL               1348
#define IDS_DUP_BROWSE                  1349
#define IDS_DUP_SCAN                    1350
#define IDS_DUP_HINT                    1351
#define IDS_DUP_MIN_SIZE                1352
#define IDS_DUP_MIN_SIZE_1KB            1353
#define IDS_DUP_MIN_SIZE_1MB            1354
#define IDS_DUP_MIN_SIZE_10MB           1355
#define IDS_DUP_KEEP                    1356
#define IDS_DUP_DELETE_EXTRAS           1357
#define IDS_DUP_DELETE_ALL_EXTRAS       1358
#define IDS_DUP_LISTING_FORMAT          1359
#define IDS_DUP_HASHING_FORMAT          1360
#define IDS_DUP_FILES_PER_SEC_FORMAT    1361
#define IDS_DUP_HASH_SPEED_FORMAT       1362
#define IDS_DUP_GROUP_FORMAT            1363
#define IDS_DUP_NO_RESULTS              1364
#define IDS_DUP_FOLDER_PLACEHOLDER      1365
#define IDS_DUP_TRUNCATED               1366
#define IDS_DUP_MIN_SIZE_DESC           1367
#define IDS_UNPIN_WORKSPACE             1368
#define IDS_ADVANCED_SEARCH             1369
#define IDS_SEARCH_CHIP_TYPE            1370
#define IDS_SEARCH_CHIP_DATE            1371
#define IDS_SEARCH_CHIP_SIZE            1372
#define IDS_SEARCH_CHIP_CONTENT         1373
#define IDS_ADV_SEARCH_NAME             1374
#define IDS_ADV_SEARCH_CONTAINS         1375
#define IDS_ADV_SEARCH_STARTS           1376
#define IDS_ADV_SEARCH_EXACT            1377
#define IDS_ADV_SEARCH_KIND             1378
#define IDS_KIND_ANY                    1379
#define IDS_KIND_FOLDER                 1380
#define IDS_KIND_DOCUMENT               1381
#define IDS_KIND_IMAGE                  1382
#define IDS_KIND_VIDEO                  1383
#define IDS_KIND_AUDIO                  1384
#define IDS_KIND_ARCHIVE                1385
#define IDS_KIND_CODE                   1386
#define IDS_KIND_CUSTOM                 1419
#define IDS_ADV_SEARCH_EXT_HINT         1420
#define IDS_ADV_SEARCH_LOCATION         1387
#define IDS_LOCATION_INDEXED            1388
#define IDS_LOCATION_CURRENT            1389
#define IDS_LOCATION_CUSTOM             1390
#define IDS_ADV_SEARCH_BROWSE           1391
#define IDS_ADV_SEARCH_DATE             1392
#define IDS_DATE_ANY                    1393
#define IDS_DATE_TODAY                  1394
#define IDS_DATE_YESTERDAY              1395
#define IDS_DATE_THIS_WEEK              1396
#define IDS_DATE_THIS_MONTH             1397
#define IDS_DATE_THIS_YEAR              1398
#define IDS_ADV_SEARCH_SIZE             1399
#define IDS_SIZE_ANY                    1400
#define IDS_SIZE_EMPTY                  1401
#define IDS_SIZE_LT_1MB                 1402
#define IDS_SIZE_1_TO_10MB              1403
#define IDS_SIZE_GT_10MB                1404
#define IDS_ADV_SEARCH_CONTENT          1405
#define IDS_CONTENT_ALL_WORDS           1406
#define IDS_CONTENT_PHRASE              1407
#define IDS_CONTENT_ANY_WORD            1408
#define IDS_ADV_SEARCH_EXCLUDE          1409
#define IDS_ADV_SEARCH_WHOLE_WORD       1410
#define IDS_ADV_SEARCH_MATCH_CASE       1411
#define IDS_ADV_SEARCH_RUN              1412
#define IDS_ADV_SEARCH_NEED_SCOPE_TITLE 1413
#define IDS_ADV_SEARCH_NEED_SCOPE_MSG   1414
#define IDS_CONTENT_CAPPED_TITLE        1415
#define IDS_CONTENT_CAPPED_MSG          1416
#define IDS_SEARCH_CONTENT_RESULTS      1417
#define IDS_ADV_SEARCH_PREVIEW          1418
#define IDS_OP_EMPTYING                 1421
#define IDS_OP_EMPTIED                  1422
#define IDS_OP_CANNOT_EMPTY             1423
#define IDS_OP_EMPTYING_SUB             1424
#define IDS_OP_PAUSE                    1425
#define IDS_OP_RESUME                   1426
#define IDS_OP_DETAILS                  1427
#define IDS_OP_SUMMARY                  1428
#define IDS_STATUS_HINT_IDLE            1429
#define IDS_STATUS_HINT_SELECTED        1430
#define IDS_STATUS_HINT_RECYCLE         1431
#define IDS_STATUS_HINT_SEARCH          1432
#define IDS_STATUS_HINT_READONLY        1433
#define IDS_SETTINGS_SHOW_PERFORMANCE   1434
#define IDS_SETTINGS_SHOW_PERFORMANCE_DESC 1435

#define IDS_SORT_BY                     1436
#define IDS_SORT_ASCENDING              1437
#define IDS_SORT_DESCENDING             1438

#define IDS_PIN_QUICK_ACCESS 1439
#define IDS_UNPIN_QUICK_ACCESS 1440
#define IDS_EFFECT_UNAVAILABLE 1441
#define IDS_INDEX_MIGRATING 1442
#define IDS_INDEX_MIGRATING_SHORT 1443
#define IDS_SETTINGS_SHOW_HIDDEN 1444
#define IDS_SETTINGS_SHOW_HIDDEN_DESC 1445
#define IDS_DOWNLOADING_UPDATE 1446
#define IDS_UPDATE_CLICK_TO_INSTALL 1447
#define IDS_UPDATE_INSTALL_FAILED 1448
#define IDS_UPDATE_CANCELLED 1449
#define IDS_UPDATE_BUSY 1450
#define IDS_INSTALLING_UPDATE 1451
#endif
